#!/bin/sh -e

#
# Remove build dependencies.
#
apk del curl make gcc g++ binutils-gold python linux-headers paxctl

#
# Remove temporary directories used by npm when building/installing.
#
rm -rf /root/.npm /root/.node-gyp

#
# Make sure temporary directories are empty, and remove apk cache.
#
rm -rf /tmp/* /var/tmp/* /var/cache/apk/*

#
# Remove Node.js installed source headers and documentation.
#
rm -rf /usr/include /usr/share/*

#
# Remove this script itself.
#
rm "$0"
